# Generated by Django 6.0.2 on 2026-02-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadhistory',
            name='quality',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
