# Generated by Django 6.0.2 on 2026-02-26 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_downloadhistory_quality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadHistory',
        ),
    ]
